version: "3.8"

services:
  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./todo-be
    container_name: nestjs-backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./todo-vue
    container_name: vue-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
